# Generated by Django 5.1.3 on 2024-11-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('tip', models.CharField(choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=10)),
                ('stok_adedi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ucak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'Akıncı'), ('KIZILELMA', 'Kızılelma')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(choices=[('KANAT', 'Kanat Takımı'), ('GOVDE', 'Gövde Takımı'), ('KUYRUK', 'Kuyruk Takımı'), ('AVIYONIK', 'Aviyonik Takımı'), ('MONTAJ', 'Montaj Takımı')], max_length=20)),
                ('sorumlu_parca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorumlu_takim', to='uretim.parca')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personeller', to='uretim.takim')),
            ],
        ),
        migrations.CreateModel(
            name='UcakParca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField()),
                ('parca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uretim.parca')),
                ('ucak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uretim.ucak')),
            ],
        ),
        migrations.AddField(
            model_name='ucak',
            name='parcalar',
            field=models.ManyToManyField(through='uretim.UcakParca', to='uretim.parca'),
        ),
    ]
