# Generated by Django 5.1.3 on 2024-11-16 10:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('uretim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='personel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='personel',
            name='isim',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='takim',
        ),
        migrations.RemoveField(
            model_name='takim',
            name='sorumlu_parca',
        ),
        migrations.AddField(
            model_name='parca',
            name='ucak_tipi',
            field=models.CharField(blank=True, choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'Akıncı'), ('KIZILELMA', 'Kızılelma')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='personel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='personel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='personel',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='personel_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='personel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='personel',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='personel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='personel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='personel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='personel',
            name='password',
            field=models.CharField(default='123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personel',
            name='takim_tipi',
            field=models.CharField(blank=True, choices=[('KANAT', 'Kanat Takımı'), ('GOVDE', 'Gövde Takımı'), ('KUYRUK', 'Kuyruk Takımı'), ('AVIYONIK', 'Aviyonik Takımı'), ('MONTAJ', 'Montaj Takımı')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='personel_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='personel',
            name='username',
            field=models.CharField(default='user', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='takim',
            name='sorumlu_parca_tipi',
            field=models.CharField(blank=True, choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='takim',
            name='sorumlu_personel',
            field=models.ManyToManyField(blank=True, related_name='takimlar', to='uretim.personel'),
        ),
        migrations.AlterField(
            model_name='parca',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parca',
            name='stok_adedi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parca',
            name='tip',
            field=models.CharField(blank=True, choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='takim',
            name='isim',
            field=models.CharField(blank=True, choices=[('KANAT', 'Kanat Takımı'), ('GOVDE', 'Gövde Takımı'), ('KUYRUK', 'Kuyruk Takımı'), ('AVIYONIK', 'Aviyonik Takımı'), ('MONTAJ', 'Montaj Takımı')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ucak',
            name='isim',
            field=models.CharField(blank=True, choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'Akıncı'), ('KIZILELMA', 'Kızılelma')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ucak',
            name='parcalar',
            field=models.ManyToManyField(blank=True, through='uretim.UcakParca', to='uretim.parca'),
        ),
        migrations.AlterField(
            model_name='ucakparca',
            name='adet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ucakparca',
            name='parca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uretim.parca'),
        ),
        migrations.AlterField(
            model_name='ucakparca',
            name='ucak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uretim.ucak'),
        ),
    ]
