# Generated by Django 5.1.3 on 2024-11-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0002_alter_personel_options_alter_personel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parca',
            name='isim',
        ),
    ]
