# Generated by Django 5.1.3 on 2024-11-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0003_remove_parca_isim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucak',
            name='stok_adedi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
